codecs:
  - name: basic_rs
    type: rs

  - name: bch4
    type: bch
    m: 11
    t: 4
    polynom: 0x2222
    chunk_size: 256
  
pipelines:
  - name: main_image
    codecs:
      - bch4

  - name: nvram
    codecs:
      - basic_rs

partitions:
  - name: main_image_part1
    pipeline: simple_ecc
    eraseblocks: 0-1021

  - name: nvram
    pipeline: nvram
    eraseblocks: 1022

  - name: main_image_part2
    pipeline: main_image
    eraseblocks: 1023
    pages: 0-60

  - name: reserved
    pipeline: 
    eraseblocks: 1023
    pages: 61-63
